/**
 * The Gridt Network API
 * Interact with the gridt network via this API. It provides several endpoints for creating and subscribing (to) movements and switching leaders.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: robin@gridt.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body { 
    username?: string;
    password?: string;
}