/**
 * The Gridt Network API
 * Interact with the gridt network via this API. It provides several endpoints for creating and subscribing (to) movements and switching leaders.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: robin@gridt.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MovementInterval { 
    /**
     * Amount of hours in between which a follower of this movement is expected to perform the action.
     */
    hours: number;
    /**
     * Amount of days in between which a follower of this movement is expected to perform the action
     */
    days: number;
    /**
     * Amount of weeks in between which a follower of this movement is expected to perform the action. example: 0
     */
    weeks?: number;
    /**
     * Amount of months in between which a follower of this movement is expected to perform the action.
     */
    months?: number;
}