import { UserId } from './userId';
/**
 * The Gridt Network API
 * Interact with the gridt network via this API. It provides several endpoints for creating and subscribing (to) movements and switching leaders.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: robin@gridt.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MovementInterval } from './movementInterval';
import { User } from './user';


export interface Movement { 
    /**
     * Name of the movement
     */
    name: string;
    id: string;
    /**
     * True if the user is subscribed to this movement.
     */
    subscribed?: boolean;

    /**
     * A comprehensive description of the movement
     */
    shortDescription: string;
    /**
     * A much longer description that is used to 'sell' a movement to it's users.
     */
    description?: string;

}